version: '3.8'

services:
  # LocalStack - AWS サービスのモック環境
  localstack:
    container_name: esiritori-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,apigateway,lambda,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - esiritori-network

  # Next.js フロントエンド開発サーバー
  frontend:
    container_name: esiritori-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
      - LOCALSTACK_ENDPOINT=http://localstack:4566
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - localstack
    networks:
      - esiritori-network
    command: pnpm dev

  # API モックサーバー（将来的にSpring Bootに置き換え）
  api-mock:
    container_name: esiritori-api-mock
    build:
      context: ./frontend/mock
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - esiritori-network

  # DynamoDB テーブル初期化
  dynamodb-init:
    container_name: esiritori-dynamodb-init
    image: amazon/aws-cli:latest
    volumes:
      - ./infrastructure/schemas:/schemas
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - esiritori-network
    entrypoint: >
      /bin/sh -c "
        echo 'Installing jq...';
        yum update -y && yum install -y jq;
        echo 'Waiting for LocalStack to be ready...';
        until aws dynamodb list-tables --endpoint-url http://localstack:4566 --region ap-northeast-1 > /dev/null 2>&1; do
          echo 'Waiting for LocalStack DynamoDB...';
          sleep 2;
        done;
        echo 'LocalStack is ready, creating tables...';
        /schemas/create-tables.sh http://localstack:4566 ap-northeast-1 /schemas/dynamodb-table-definitions.json;
        echo 'Tables created successfully!';
      "

  # DynamoDB 管理UI - LocalStackのDynamoDBを表示・管理
  dynamodb-admin:
    container_name: esiritori-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - dynamodb-init
    networks:
      - esiritori-network

networks:
  esiritori-network:
    driver: bridge

volumes:
  localstack-data:
