version: '3.8'

services:
  # LocalStack - AWS サービスのモック環境
  localstack:
    container_name: esiritori-localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=dynamodb,apigateway,lambda,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - esiritori-network

  # Next.js フロントエンド開発サーバー
  frontend:
    container_name: esiritori-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
      - LOCALSTACK_ENDPOINT=http://localstack:4566
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - localstack
    networks:
      - esiritori-network
    command: pnpm dev

  # API モックサーバー（将来的にSpring Bootに置き換え）
  api-mock:
    container_name: esiritori-api-mock
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    networks:
      - esiritori-network

networks:
  esiritori-network:
    driver: bridge

volumes:
  localstack-data:
