version: '3.8'

services:
  # DynamoDB Local - DynamoDB開発環境
  dynamodb-local:
    container_name: esiritori-dynamodb-local
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    networks:
      - esiritori-network

  # Next.js フロントエンド開発サーバー
  frontend:
    container_name: esiritori-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:3001
      - NEXT_PUBLIC_WS_URL=ws://localhost:3001
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - dynamodb-local
    networks:
      - esiritori-network
    command: pnpm dev

  # API モックサーバー（将来的にSpring Bootに置き換え）
  api-mock:
    container_name: esiritori-api-mock
    build:
      context: ./frontend/mock
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - dynamodb-local
    networks:
      - esiritori-network

  # DynamoDB テーブル初期化
  dynamodb-init:
    container_name: esiritori-dynamodb-init
    image: amazon/aws-cli:latest
    volumes:
      - ./infrastructure/schemas:/schemas
    environment:
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - dynamodb-local
    networks:
      - esiritori-network
    entrypoint: >
      /bin/sh -c "
        echo 'Installing jq...';
        yum update -y && yum install -y jq;
        echo 'Waiting for DynamoDB Local to be ready...';
        until aws dynamodb list-tables --endpoint-url http://dynamodb-local:8000 --region ap-northeast-1 > /dev/null 2>&1; do
          echo 'Waiting for DynamoDB Local...';
          sleep 2;
        done;
        echo 'DynamoDB Local is ready, creating tables...';
        /schemas/create-tables.sh http://dynamodb-local:8000 ap-northeast-1 /schemas/dynamodb-table-definitions.json;
        echo 'Tables created successfully!';
      "

  # DynamoDB 管理UI - DynamoDB LocalのDBを表示・管理
  # http://127.0.0.1:8001/
  dynamodb-admin:
    container_name: esiritori-dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      - AWS_REGION=ap-northeast-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - dynamodb-init
    networks:
      - esiritori-network

networks:
  esiritori-network:
    driver: bridge

volumes:
  localstack-data:
